version: '3.9'

services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: user
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - ./src:/var/www/html/wp-content/plugins/meu-plugin

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    platform: linux/x86_64

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8888:8080

networks:
  back:

volumes:
  db:
